"""
Exercise 3: Breakout activity, the DataCleaner class

Work together in a breakout room to fill in the missing methods. You have a DataCleaner class that wraps a pandas
DataFrame. Add three methods, using Copilot's suggestions and Tab Completion to help, but
read every suggestion before you accept it.

  1. drop_missing()        - drop rows with any missing values
  2. drop_duplicate_rows() - remove duplicate rows
  3. summary()             - return summary statistics for the DataFrame

Once you have finished writing the methods using Copilot's Tab Completion, 
run this file and analyze how well Copilot wrote this DataCleaner class by answering the questions at the bottom of this file. 
"""

import pandas as pd


class DataCleaner:
    def __init__(self, dataframe):
        self.df = dataframe

    def drop_missing(self):
        # Drop rows with any missing values, updating self.df in place.
        
        '''
        Copilot suggestion:
        self.df.dropna(inplace=True)
        '''

        self.df = self.df.dropna()

    def drop_duplicate_rows(self):
        # Remove duplicate rows, updating self.df in place.
        '''
        Copilot suggestion:
        self.df.drop_duplicates(inplace=True)'
        '''
        self.df = self.df.drop_duplicates()

    def summary(self):
        # Return summary statistics for the DataFrame.
        '''
        Copilot suggestion:
        return self.df.describe()
        '''
        return self.df.describe() 

if __name__ == "__main__":
    df = pd.read_csv("sample_data.csv")  
    cleaner = DataCleaner(df)  
    cleaner.drop_missing()
    cleaner.drop_duplicate_rows()
    print(cleaner.df)
    print(cleaner.summary())

# once you have finished writing and running the code, discuss the following questions:
# 1. Where in your AI Studio project could Copilot genuinely save you time?
# 2. What's one risk you want to watch for as you use it?
# 3. What's one norm you want to commit to as a team for how you'll use it?

'''
Penny voice:
1. Faster than raw coding.
2. Hallucinations, also it doesn't give you the best/most efficient or optimal code.
3. Always sanity check. Rage-bait the AI if necessary -> 
are you sure? 
where did you get this logic from? 
Never blindly accept suggestions. 
Garbage in -> Garbage out
'''

'''
Co-pilot suggestions:
1. Copilot can save time by suggesting code snippets, completing functions, and providing documentation or comments for the code. It can also help with repetitive tasks like writing boilerplate code or generating test cases.
2. One risk to watch for is that Copilot may suggest code that is incorrect, insecure, or not aligned with the project's requirements. It's important to review and understand the suggestions before accepting them
3. One norm to commit to as a team is to always review and test the code generated by Copilot, ensuring that it meets the project's standards and requirements. Additionally, team members should communicate and collaborate on how to best utilize Copilot's suggestions while maintaining code quality and consistency.
'''

# Optional extension (if you finish early): Use GitHub Copilot to write a new Python file that:
#      1. Loads extension_clustering_data.csv
#      2. Cleans it the same way your DataCleaner class does (drop missing values, drop duplicates)
#      3. Fits a K-means model with 2 clusters on the age and score columns, using scikit-learn
